// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP1Td43txEVleom5ApSfxm7Wz_eBUtjXI',
    appId: '1:528265556723:web:b3f91403a91f1a9ce2bd86',
    messagingSenderId: '528265556723',
    projectId: 'qarocarapp',
    authDomain: 'qarocarapp.firebaseapp.com',
    storageBucket: 'qarocarapp.firebasestorage.app',
    measurementId: 'G-Y2H5SY56H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRpd3ztv01jV80BxkLpxGK1BSg_s2VW2A',
    appId: '1:528265556723:android:dd13db5176af980ce2bd86',
    messagingSenderId: '528265556723',
    projectId: 'qarocarapp',
    storageBucket: 'qarocarapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_GzD2XPzl6YIboA3_nvtUD_Q25XV5OC4',
    appId: '1:528265556723:ios:50ef91db5d185e57e2bd86',
    messagingSenderId: '528265556723',
    projectId: 'qarocarapp',
    storageBucket: 'qarocarapp.firebasestorage.app',
    iosClientId: '528265556723-o2arpcnt2d5ac852581nnf0qhtsj7b9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.qaro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_GzD2XPzl6YIboA3_nvtUD_Q25XV5OC4',
    appId: '1:528265556723:ios:50ef91db5d185e57e2bd86',
    messagingSenderId: '528265556723',
    projectId: 'qarocarapp',
    storageBucket: 'qarocarapp.firebasestorage.app',
    iosClientId: '528265556723-o2arpcnt2d5ac852581nnf0qhtsj7b9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.qaro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP1Td43txEVleom5ApSfxm7Wz_eBUtjXI',
    appId: '1:528265556723:web:b4234a397a3efea5e2bd86',
    messagingSenderId: '528265556723',
    projectId: 'qarocarapp',
    authDomain: 'qarocarapp.firebaseapp.com',
    storageBucket: 'qarocarapp.firebasestorage.app',
    measurementId: 'G-BKF4VF0JF6',
  );

}